vich_uploader:
    db_driver: orm

    mappings:
        cv_photos:
            uri_prefix: /uploads/cv/photos
            upload_destination: '%kernel.project_dir%/public/uploads/cv/photos'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
