# config/services.yaml

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Controllers are imported separately to make sure services can be injected
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # DOMPDF Configuration
    Dompdf\Dompdf:
        calls:
            - [setOptions, ['@dompdf.options']]

    dompdf.options:
        class: Dompdf\Options
        calls:
            - [set, ['defaultFont', 'Inter']]
            - [set, ['isRemoteEnabled', true]]
            - [set, ['isHtml5ParserEnabled', true]]
            - [set, ['isFontSubsettingEnabled', true]]
            - [set, ['debugPng', false]]
            - [set, ['debugKeepTemp', false]]
            - [set, ['debugCss', false]]
            - [set, ['debugLayout', false]]
            - [set, ['debugLayoutLines', false]]
            - [set, ['debugLayoutBlocks', false]]
            - [set, ['debugLayoutInline', false]]
            - [set, ['debugLayoutPaddingBox', false]]